<a href="https://colab.research.google.com/github/knagabharathi/Python/blob/main/FITBIT_casestudies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files

# Use the files.upload() function to upload a file from your local machine
uploaded = files.upload()

Saving fit.txt to fit.txt


In [8]:
import numpy as np
data = np.loadtxt('fit.txt',dtype=str)
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [9]:
data.shape

(96, 6)

In [10]:
date , step_count, mood, calories_burned, hours_of_sleep, activity_status = data.T

In [12]:
date[:10]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017'], dtype='<U10')

In [13]:
calories_burned[:10]

array(['181', '197', '0', '174', '223', '149', '140', '38', '1', '40'],
      dtype='<U10')

In [15]:
step_count = np.array(step_count, dtype = int)
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [17]:
calories_burned = np.array(calories_burned, dtype = int)
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [18]:
hours_of_sleep = np.array(hours_of_sleep, dtype = int)
hours_of_sleep

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

### Step_count, calories_burned , Mood

In [19]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [20]:
np.unique(activity_status )

array(['Active', 'Inactive'], dtype='<U10')

Average step count

In [22]:
np.mean(step_count)

2935.9375

On which day the step count was highest and the caloires burned

In [23]:
# more steps count more calories burned
np.max(step_count)

7422

In [24]:
np.argmax(step_count)

69

In [25]:
date[69]

'14-12-2017'

In [26]:
date[np.argmax(step_count)]

'14-12-2017'

In [27]:
calories_burned[np.argmax(calories_burned)]

243

How to find top 5 maximum step count

In [29]:
np.sort(step_count)[::-1][:5]

array([7422, 7102, 6930, 6915, 6676])

Steps count vs Mood

In [30]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [32]:
np.mean(step_count[mood=='Sad'])

2103.0689655172414

In [35]:
np.mean(step_count[mood=='Happy'])

3392.725

What is my mood when step_count > 4000

In [37]:
mood[step_count>4000]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [39]:
np.unique(mood[step_count>4000], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

What is my mood when step count < 2000

In [42]:
np.unique(mood[step_count < 2000], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))

Home work

1) Hoursof sleep , activity_status - formulate question