<a href="https://colab.research.google.com/github/knagabharathi/Python/blob/main/ImageManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [3]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [4]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [6]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
x

array([  5,  -9,  20,  25,   3,  -5,  16, -10,  -8])

In [7]:
import numpy as np
arr = 2*np.arange(0,2,0.5)
if arr <= 0.6:
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy")

ValueError: ignored

In [8]:
a = np.arange(10,22).reshape((3, 4))

print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [9]:
import numpy as np

a = np.array([[6, 28], [8, 56], [7, 19]])

x=np.transpose(a).reshape(1,6)

print(x)

[[ 6  8  7 28 56 19]]


In [10]:
a = np.array([[16, 5], [81, 6], [33, 1]])

x=np.transpose(a).reshape(2,3)

print(x.flatten())

[16 81 33  5  6  1]


In [11]:
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])

print(a.transpose()[-2,-2])

56


In [6]:
import numpy as np
arr1 = np.array([1,2,3,6,3,2])

arr2 = np.array([4,2,1,3,3,2])

arr3 = np.zeros(len(arr1))

np.zeros(len(arr1))

arr3 = arr1*arr2
arr3

x = np.where(arr1 > 0, 1, -1)
x

array([1, 1, 1, 1, 1, 1])

In [7]:
for i in range(len(arr1)):

    if(arr1[i] < 0 ):

        arr1[i] = -1

    else:

        arr1[i] = 1

arr1

array([1, 1, 1, 1, 1, 1])

In [8]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [10]:
arr = [-1,2,3,-4,5]
target = 3

x= np.argwhere(np.array(arr)>target)
x

array([[4]])

In [15]:
arr =[8, 12, 16, 20]
key = 4

m = (np.array(arr) % key == 0)

if m.all() == True :
  print('1')

1


In [21]:
x = [[1,2,3],
 [4,5,6],
 [7,8,9]]

c =x[::-1]

l =np.transpose(np.array(c))
l

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [25]:
x = [[1,2,3],
 [4,5,6],
 [7,8,9]]

l =np.array(x)[:,::-1]
l

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [34]:
k = 4
x = np.zeros((k,k))
np.fill_diagonal(x,k)
x

array([[4., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 4.]])

In [8]:
import numpy as np

arr = np.array([-3, 4, 27, 34, -2, 0, -45, -11, 4, 0])
#arr

np.where(arr<0,1, -1)

array([ 1, -1, -1, -1,  1, -1,  1,  1, -1, -1])

In [12]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
A = np.arange(9).reshape(3,3)
A
#print(A[[1,0,2], :])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
print(A[[1,0,2],:])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [18]:
print(A[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [38]:
import numpy as np
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(X[row[:, np.newaxis], mask])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [23]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [22]:
mask = np.array([1, 0, 1, 0], dtype=bool)
mask

array([ True, False,  True, False])

In [20]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
row = np.array([0, 1, 2])
row

array([0, 1, 2])

In [26]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [27]:
mask

array([ True, False,  True, False])

In [25]:
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [37]:
X[row[:,np.newaxis],mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [40]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
import numpy as np
X = np.arange(12).reshape(3,4)

X.max(axis=1) #=> [ 3, 7, 11]
#X.sum() #=> 11
#X.T.max(axis=0) #=> [ 3, 7, 11]
#[i.min() for i in X] #=> [0, 4, 8]

array([ 3,  7, 11])

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [11]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [12]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [13]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [14]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [15]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [16]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [17]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [18]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0


In [19]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])

21


In [55]:
import numpy as np
a = [[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]]

x =np.array(a)
b= x[2:,1:]
#x[[1,2,2],[3,3,1]]

b[0],b[1] = b[1].copy(),b[0].copy()
b

array([[13, 14, 15],
       [ 9, 10, 11],
       [17, 18, 19]])

In [8]:
import numpy as np
X = np.arange(12).reshape(3,4)
#X.max(axis=1) #=> [ 3, 7, 11]
X.sum() #=> 11 -66
#X.T.max(axis=0) #=> [ 3, 7, 11]
#l=[i.min() for i in X] #=> [0, 4, 8]
#l

66

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [10]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [11]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [12]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [14]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [15]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [16]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [17]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0


In [18]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])

21


In [37]:
a = np.arange(9).reshape(3,3)
a[1,0]

3

In [50]:
value = 300
matrix = np.eye(3, dtype=np.int32) * value
matrix

array([[300,   0,   0],
       [  0, 300,   0],
       [  0,   0, 300]], dtype=int32)