<a href="https://colab.research.google.com/github/knagabharathi/Python/blob/main/Model_test_python_lib2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np,pandas as pd

In [19]:
a = np.arange(1,100).reshape(3,33)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]])

In [24]:
b = np.hsplit(a,3)
b

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
        [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77]]),
 array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
        [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88]]),
 array([[23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
        [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
        [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [25]:
c=np.sum(b,axis=0)
c

array([[ 36,  39,  42,  45,  48,  51,  54,  57,  60,  63,  66],
       [135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165],
       [234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264]])

In [26]:
np.sum(c,axis=1)

array([ 561, 1650, 2739])

#Mean of the first row

In [29]:
a = np.arange(0,10)

In [35]:
even = a[a%2 == 0]

In [36]:
odd =a[a%2 != 0]

In [40]:
s = np.hstack((even,odd))
s

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [46]:
x = s.reshape(2,5)

In [47]:
x[0]

array([0, 2, 4, 6, 8])

In [48]:
np.mean(x[0])

4.0

#greater bill and tip

In [49]:
import seaborn as sns
df= sns.load_dataset('tips')

In [55]:
df[(df['total_bill'] >  20 )&(df['tip']> 4)]

(37, 7)

#shape of the stacked array

In [56]:
a = np.arange(1,11)

In [59]:
even = a[a%2 == 0]

In [60]:
odd = a[a%2 != 0]

In [61]:
s = np.vstack((even,odd))

In [63]:
s.shape

(2, 5)

#maximum occurances

In [64]:
import seaborn as sns
df= sns.load_dataset('tips')

In [69]:
df[df['total_bill'].between(20,30)].shape

(65, 7)

In [71]:
df[df['total_bill'].between(10,20)].shape

(130, 7)

In [72]:
df[df['total_bill'].between(30,40)].shape

(22, 7)

In [73]:
df[df['total_bill'].between(40,50)].shape

(9, 7)

#Vertically stacked mean

In [74]:
a = np.arange(1,11)

In [77]:
s = np.vstack(((a[a%2 == 0]),(a[a%2 !=0])))
s

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [82]:
x = s[:,3:].mean(axis=0)

In [84]:
x.mean(axis=0)

8.5

#highest passengers

In [85]:
link = "https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/033/327/original/flights.csv?1683012330"
df= pd.read_csv(link)

In [86]:
df

year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [93]:
df.groupby(['year','month']).aggregate({'passengers':'sum'})

passengers
year month            
1949 Apr           129
     Aug           148
     Dec           118
     Feb           118
     Jan           112
...                ...
1960 Mar           419
     May           472
     Nov           390
     Oct           461
     Sep           508

[144 rows x 1 columns]

In [97]:
x = df['passengers'].max()

In [99]:
df[df['passengers'] == x]

year month  passengers
138  1960   Jul         622

#sum of squares

In [100]:
a = np.arange(1,21)

In [102]:
a[a%2 == 0 ] ** 2

array([  4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [103]:
array = np.array([i**2 if i%2 == 0 else i for i in a])
array

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100,  11, 144,  13,
       196,  15, 256,  17, 324,  19, 400])

In [112]:
x = array.reshape(10,2)
x

array([[  1,   4],
       [  3,  16],
       [  5,  36],
       [  7,  64],
       [  9, 100],
       [ 11, 144],
       [ 13, 196],
       [ 15, 256],
       [ 17, 324],
       [ 19, 400]])

In [111]:
x[:,-1]

array([  4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [110]:
x[:,-1].sum()

1540