<a href="https://colab.research.google.com/github/knagabharathi/Python/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy


In [3]:
import numpy as np

np.arange(22,71,2)
np.arange(21,72,2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [8]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
#float(arr)
#arr.tofloat()
arr.astype('float64')
#type(arr, dtype='float64')

array([10., 20., 30., 40., 50.])

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[-2])

6


In [11]:
import numpy as np

a = np.arange(10)

print(a[2:5])
a

[2 3 4]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
import numpy as np
np.arange(1,20,2)
np.arange(20,0,-2)

res = np.multiply(np.arange(20,0,-2), np.arange(1,20,2))
res
print(np.subtract(np.max(res),np.min(res)))

90


In [17]:

np.size([0,1,2,3,4,5])
arr= np.array([0,1,2,3,4,5])
print(arr.shape)

print(arr.ndim)

(6,)
1


In [28]:
import numpy as np
arr= [-2, -1, 0, 1, 2]
x = np.array(arr)
z = np.exp(-x)

denom = 1+z

result = 1/denom
result

result = np.round(result,decimals=2 )
result

array([0.12, 0.27, 0.5 , 0.73, 0.88])

In [3]:
import numpy as np

def create_seq(start, end, step):

    arr = np.arange(start,end,step)
    x = np.round(arr, decimals=2)

    return x

create_seq(5,7,0.5)

array([5. , 5.5, 6. , 6.5])

In [4]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

import numpy as np
x=[]
for b,a in zip(birds,age):
  if b == 'Cranes':
    x.append(a)

l = np.array(x)
summ = np.mean(l)
summ

4.75

In [22]:


def comm(birds,age):
  com = sorted(zip(age,birds))
  com

  a,b = zip(*com)
  return list(b)

birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
comm(birds,age)

['plovers',
 'plovers',
 'plovers',
 'plovers',
 'plovers',
 'Cranes',
 'Cranes',
 'spoonbills',
 'plovers',
 'spoonbills']